### PR TITLE
Fixes macOS, watchOS and tvOS compile errors

### PR DESCRIPTION
**Pull request by mmllr**

### CODE REVIEW

**Comment by abadikaka** [comment]
thanks for the PR! I will merge it soon after I review it @mmllr

**Review by abadikaka — APPROVED** [review]

**Comment by mmllr** [comment]
👍 Could you ad a new tag?

**Comment by mmllr** [comment]
> thanks for the PR! I will merge it soon after I review it @mmllr

Could you add a new version with a tag?

**Comment by abadikaka** [comment]
surely will do @mmllr

**Comment by abadikaka** [comment]
added new release tag 5.0.0 @mmllr

**Pull request merged**
